package com.example.demosb;


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;


@RestController
public class TestController {
    @Autowired
    User userOne; //- this is a bean of User class, created by @Component annotation in User class / spring bean
    @GetMapping("get-msg")
    public User getMsg() {
        //User userOne = new User(1L, "John", 30); //user UserOne is an instance of User class or java bean
        userOne.setId(1l); //- setting id to null, so that it will be generated by the database
        userOne.setName("John Doe");
        userOne.setAge(30);
        return userOne;
    }
    
    
}
